apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary
spec:
  replicas: 5
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: scala-hello-world
      component: backend
  template:
    metadata:
      labels:
        app: scala-hello-world
        component: backend
    spec:
      containers:
      - name: scala-hello-world
        image: docker.io/ajpahl1008/scala-hello-world-backend:41
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
  strategy:
    canary:
      canaryService: scala-backend-rollout
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 80
      - pause: {}
      - setWeight: 100
