apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pipelines-appsets-argocd-rollouts
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:harness-ajp/argo-example-apps.git
              revision: HEAD
              files:
                - path: "scala-hello/cluster-config/backend/config.json"
          - git:
              repoURL: git@github.com:harness-ajp/argo-example-apps.git
              revision: HEAD
              files:
                - path: "scala-hello/cluster-config/frontend/config.json"
  template:
    spec:
      source:
        kustomize:
          images:
            - name: backend-image
              newName: ajpahl1008/scala-hello-world-backend
              newTag: '{{.backend_tag}}'
            - name: frontend-image
              newName: ajpahl1008/scala-hello-world-frontend
              newTag: '{{.frontend_tag}}'
      destination:
        server: '{{.server_address}}'
        namespace: 'scala-apps-{{.environment}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - PruneLast=true
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
